# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- netlify.toml

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Projects
  url: /projects/
- title: Publications
  url: /publications/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  project_post:
    title: Past Projects and Experiences
    output: true
    description: "The cumulation of all my past projects and experiences during the four year of study"
    feature_text: |
      Welcome to my projects
    feature_image: "https://picsum.photos/2560/600?image=866"
  publication_post:
    title: List of publications
    output: true
    description: "The cumulation of all my publications"
    feature_text: |
      Welcome to my publications
    feature_image: "https://picsum.photos/2560/600?image=866"
# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
